/*
 * Nick Dernovsek
 * This program is a cs:go tutorial for noobs
 * by using multiple jpanels and two jFrames
 */

package DynamicPanelPakage;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author nider6687
 */
public class DynamicPanelForm extends javax.swing.JFrame {
    GridBagLayout layout = new GridBagLayout();
    PanelHome pHome;
    PanelRecoil pRecoil;
    PanelStrafing pStrafing;
    PanelGrenade pGrenade;     
    PanelBuyMenu pBuyMenu;
    PanelBuy pBuy;
    PanelMaps pMaps;
    PanelHelp pHelp;
    PanelMovement pMovement;
    /**
     * Creates new form DynamicPanelForm
     */
    
    public DynamicPanelForm() {
        initComponents();
        pHome = new PanelHome();
        pRecoil = new PanelRecoil();
        pStrafing = new PanelStrafing();
        pGrenade = new PanelGrenade();
        pBuyMenu = new PanelBuyMenu();
        pBuy = new PanelBuy();
        pMaps = new PanelMaps();
        pHelp = new PanelHelp();
        pMovement = new PanelMovement();
        
        dynamicPanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        
        dynamicPanel.add(pHome,c);
        dynamicPanel.add(pRecoil,c);
        dynamicPanel.add(pStrafing,c);
        dynamicPanel.add(pGrenade,c);
        dynamicPanel.add(pBuyMenu,c);
        dynamicPanel.add(pBuy,c);
        dynamicPanel.add(pMaps,c);
        dynamicPanel.add(pHelp,c);
        dynamicPanel.add(pMovement,c);
    
        pBuy.setVisible(false);
        pBuyMenu.setVisible(false);
        pMaps.setVisible(false);
        pGrenade.setVisible(false);       //sets all panels to visible false except the home menu panel
        pStrafing.setVisible(false);
        pHelp.setVisible(false);
        pMovement.setVisible(false);
        pRecoil.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dynamicPanel = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        movementButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        helpButton = new javax.swing.JButton();
        testButton = new javax.swing.JButton();
        subTitleLabel = new javax.swing.JLabel();
        recoilButton = new javax.swing.JButton();
        strafingButton = new javax.swing.JButton();
        buyMenuButton = new javax.swing.JButton();
        buyButton = new javax.swing.JButton();
        mapsButton = new javax.swing.JButton();
        grenadeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dynamicPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dynamicPanel.setAlignmentX(0.0F);

        javax.swing.GroupLayout dynamicPanelLayout = new javax.swing.GroupLayout(dynamicPanel);
        dynamicPanel.setLayout(dynamicPanelLayout);
        dynamicPanelLayout.setHorizontalGroup(
            dynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        dynamicPanelLayout.setVerticalGroup(
            dynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        movementButton.setText("Movement");
        movementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movementButtonActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("SerpentineDEEBol", 1, 18)); // NOI18N
        titleLabel.setText("Cs:Go for Noobs");

        helpButton.setText("Help");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        testButton.setText("Take the Test!");
        testButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testButtonActionPerformed(evt);
            }
        });

        subTitleLabel.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 14)); // NOI18N
        subTitleLabel.setText("A cs:go tutoral program");

        recoilButton.setText("Recoil Control");
        recoilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recoilButtonActionPerformed(evt);
            }
        });

        strafingButton.setText("Counter Strafing");
        strafingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strafingButtonActionPerformed(evt);
            }
        });

        buyMenuButton.setText("Intro to the buy menu");
        buyMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyMenuButtonActionPerformed(evt);
            }
        });

        buyButton.setText("What to buy?");
        buyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyButtonActionPerformed(evt);
            }
        });

        mapsButton.setText("All the Maps");
        mapsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapsButtonActionPerformed(evt);
            }
        });

        grenadeButton.setText("Grenade Usage");
        grenadeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grenadeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(helpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(testButton)
                .addGap(30, 30, 30)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(subTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buyButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buyMenuButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(grenadeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(strafingButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(recoilButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(movementButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mapsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(dynamicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(helpButton)
                    .addComponent(homeButton)
                    .addComponent(testButton)
                    .addComponent(subTitleLabel))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(movementButton)
                        .addGap(41, 41, 41)
                        .addComponent(recoilButton)
                        .addGap(41, 41, 41)
                        .addComponent(strafingButton)
                        .addGap(50, 50, 50)
                        .addComponent(grenadeButton)
                        .addGap(50, 50, 50)
                        .addComponent(buyMenuButton)
                        .addGap(49, 49, 49)
                        .addComponent(buyButton)
                        .addGap(44, 44, 44)
                        .addComponent(mapsButton)
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addComponent(dynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * This method sets all of the panels to visible(false)
     * so that they don't overlap
     */
    public void visibleFalse() {
    pHome.setVisible(false);
    pBuy.setVisible(false);
    pBuyMenu.setVisible(false);
    pMaps.setVisible(false);
    pGrenade.setVisible(false);         //sets all the panels to visible(false)
    pStrafing.setVisible(false);
    pHelp.setVisible(false);
    pMovement.setVisible(false);
    pRecoil.setVisible(false);
}
    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
       visibleFalse();
       pHome.setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void movementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movementButtonActionPerformed
        visibleFalse();
        pMovement.setVisible(true);
    }//GEN-LAST:event_movementButtonActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        visibleFalse();
        pHelp.setVisible(true);
    }//GEN-LAST:event_helpButtonActionPerformed

    private void buyMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyMenuButtonActionPerformed
        visibleFalse();
        pBuyMenu.setVisible(true);
    }//GEN-LAST:event_buyMenuButtonActionPerformed

    private void mapsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapsButtonActionPerformed
        visibleFalse();
        pMaps.setVisible(true);
    }//GEN-LAST:event_mapsButtonActionPerformed

    private void testButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testButtonActionPerformed
        TestFrame test = new TestFrame();
        test.setVisible(true);
    }//GEN-LAST:event_testButtonActionPerformed

    private void grenadeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grenadeButtonActionPerformed
        visibleFalse();
        pGrenade.setVisible(true);
    }//GEN-LAST:event_grenadeButtonActionPerformed

    private void recoilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recoilButtonActionPerformed
        visibleFalse();
        pRecoil.setVisible(true);
    }//GEN-LAST:event_recoilButtonActionPerformed

    private void strafingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strafingButtonActionPerformed
        visibleFalse();
        pStrafing.setVisible(true);
    }//GEN-LAST:event_strafingButtonActionPerformed

    private void buyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyButtonActionPerformed
        visibleFalse();
        pBuy.setVisible(true);
    }//GEN-LAST:event_buyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DynamicPanelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DynamicPanelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DynamicPanelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DynamicPanelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DynamicPanelForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyButton;
    private javax.swing.JButton buyMenuButton;
    private javax.swing.JPanel dynamicPanel;
    private javax.swing.JButton grenadeButton;
    private javax.swing.JButton helpButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton mapsButton;
    private javax.swing.JButton movementButton;
    private javax.swing.JButton recoilButton;
    private javax.swing.JButton strafingButton;
    private javax.swing.JLabel subTitleLabel;
    private javax.swing.JButton testButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
