/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DynamicPanelPakage;

/**
 *
 * @author nickd
 */
public class PanelBuyMenu extends javax.swing.JPanel {
    /**
     * Creates new form Panel5
     */
    public PanelBuyMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buyMenuLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pistolsButton = new javax.swing.JButton();
        heavyButton = new javax.swing.JButton();
        smgsButton = new javax.swing.JButton();
        riflesButton = new javax.swing.JButton();
        gearButton = new javax.swing.JButton();
        grenadesButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        weaponsArea = new javax.swing.JTextArea();

        buyMenuLabel.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        buyMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buyMenuLabel.setText("What is the Buy Menu?");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DynamicPanelPakage/buymenu.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setText("The buy meun which is hotkeyed B by defualt,");

        jLabel4.setText("The buy menu has six categories: ");

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel5.setText("-Pistols (1)");

        jLabel6.setText("is the menu where you buy everything. lol");

        jLabel7.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel7.setText("-Gear (5)");

        jLabel8.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel8.setText("-Heavy (2)");

        jLabel9.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel9.setText("-SMGs (3)");

        jLabel10.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel10.setText("-Rifles (4)");

        jLabel11.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel11.setText("-Grenades (6)");

        jLabel12.setText("Below are six buttons that show what is in each category and what they do:");

        pistolsButton.setText("Pistols");
        pistolsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pistolsButtonActionPerformed(evt);
            }
        });

        heavyButton.setText("Heavy");
        heavyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heavyButtonActionPerformed(evt);
            }
        });

        smgsButton.setText("SMGs");
        smgsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smgsButtonActionPerformed(evt);
            }
        });

        riflesButton.setText("Rifles");
        riflesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riflesButtonActionPerformed(evt);
            }
        });

        gearButton.setText("Gear");
        gearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gearButtonActionPerformed(evt);
            }
        });

        grenadesButton.setText("Grenades");
        grenadesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grenadesButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBar(null);

        weaponsArea.setEditable(false);
        weaponsArea.setColumns(20);
        weaponsArea.setRows(5);
        weaponsArea.setText("Press one of the six buttons...");
        jScrollPane1.setViewportView(weaponsArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buyMenuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(pistolsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(heavyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(smgsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(riflesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grenadesButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buyMenuLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pistolsButton)
                    .addComponent(heavyButton)
                    .addComponent(smgsButton)
                    .addComponent(riflesButton)
                    .addComponent(gearButton)
                    .addComponent(grenadesButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void heavyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heavyButtonActionPerformed
        weaponsArea.setText("Heavy: Sawed-off, Nova, Mag-7, XM1040, M249 and the Negev\n"
                + "\nThere are two types of Heavies, shotguns which include the Sawed-off, Nova, Mag-7"
                + "\nand the XM1040. Shotguns should be used at very close ranges for one shot kills."
                + "\nThe other types of heavies are the LMGs which include the M249 and the Negev."                     //very basic code for setting text
                + "\nLMGs should rarely be bought but are used for spamming smokes to get a free kill.");
    }//GEN-LAST:event_heavyButtonActionPerformed

    private void pistolsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pistolsButtonActionPerformed
        weaponsArea.setText("Pistols: P2000/USP-S, Dual Berettas P250, Five-Seven/Tec9/Cz-75 Auto, Deagle\n"
                + "\nPistols are the cheapest weapons in cs:go but they do the least amount"
                + "\nof damage. Pistols should be used at close to mid ranges because of the"
                + "\ndamage falloff. The one exception to this is the Desert Eagle, which"
                + "\nshould be used at a long range due to it's one shot headshot kill reward.");
    }//GEN-LAST:event_pistolsButtonActionPerformed

    private void smgsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smgsButtonActionPerformed
        weaponsArea.setText("SMGs: MP9, UMP9, MP7, PP-Bizon and the P90\n"
                + "\nSMGs are cs:go's run and gun weapon. They are very easy to use and take almost"
                + "\nno skill because they require very little recoil control (see recoil control)."
                + "\nThese guns should be bought when you don't have enough money to buy a rifle"
                + "\nor when you're new to the game. They should be used at medium to close ranges.");
    }//GEN-LAST:event_smgsButtonActionPerformed

    private void riflesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riflesButtonActionPerformed
        weaponsArea.setText("Rifles: Famas/galilar, AK-47, M4A4/M4a1s, SSG08, AWP, Scar 20\n "
                + "\nRifles are the go to weapons in counter strike. They are the best, most"
                + "\nefficent and are very pricey but they are the hardest to master. There are"
                + "\ntwo types of rifles, normal ones and scoped ones. The AWP, which is the most"
                + "\nfamous scoped rifle is a one shot kill to the body and head. Non-scoped rifles"
                + "\ncan be used at all distances but scoped rifles are spicifically long ranged weapons.");
    }//GEN-LAST:event_riflesButtonActionPerformed

    private void gearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gearButtonActionPerformed
        weaponsArea.setText("Gear: Zeus, Kevlar, Kevlar+Helmet and the diffuse kit for CT only\n"
                + "\nGear in counter strike is just the others category basically. The zeus is"
                + "\na very cheap shotgun that can only be used once but is a one shot kill if"
                + "\nclose enough. Kevlar and a helmet should be bought every round when possible"
                + "\n.");
    }//GEN-LAST:event_gearButtonActionPerformed

    private void grenadesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grenadesButtonActionPerformed
        weaponsArea.setText("Grenades: Molotov/Incendiary, High explosive grenade, decoy and flashbang\n"
                + "\nSee Grenade Usage for more info on grenades");
    }//GEN-LAST:event_grenadesButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buyMenuLabel;
    private javax.swing.JButton gearButton;
    private javax.swing.JButton grenadesButton;
    private javax.swing.JButton heavyButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pistolsButton;
    private javax.swing.JButton riflesButton;
    private javax.swing.JButton smgsButton;
    private javax.swing.JTextArea weaponsArea;
    // End of variables declaration//GEN-END:variables
}
